### ISSUE TITLE
Bugs in simplify_network.py

### ISSUE THREAD

**Issue by hazemakhalek** [pz-max/pypsa-africa#112]
The script `simplify_network.py ` script is working but still have a couple of issues:

- [x] remove_stubs function removes all the lines from the network
This function is currently commented out in the script. I'm still not sure whether is happens due to a bug here or is it a problem from the network topology. [temporarily solved, but to be improved]

- [x] the wildcard ` simpl` creates problems with the network build
The wildcard allows you to cluster the network within the `simplify_network` preliminarily before running the `cluster_network` script. I'm still not sure why is this useful especially that is alwys skipped in PyPSA-EUR. As long as you is skipped, the script runs fine.

- [x] `def simplify_network_to_380` is not stable. If countries have no single 380 kV line the function breaks. Probably the `Linetype` must be read out differently and the filtering approaches adjusted.

**Comment by pz-max** [comment]
@Hazem-IEG , added the observed bug above. `def simplify_network_to_380`

**Comment by pz-max** [comment]
Third point (def simplify_network_to_380) fixed by commit https://github.com/pypsa-meets-africa/pypsa-africa/commit/505b9746b05bdb1730ab748385f90461717da31c

**Comment by davide-f** [comment]
The issue (1) is related to the fact that in our case, multiple buses correspond to the same substation. 
In the last commits ( 69f0475c6e01cd0acf1166193dfb29e13b9d7cd7 - ab0367f874a78158b5f417993cd45ab62deb7e8c ), first I improved how those nodes are identified, then I introduced a very basic trick: add "fake lines" between the nodes corresponding to the same substations. With this trick, the remove_stubs work, but I don't think we should keep this basic trick.
I think we should "merge" nodes corresponding to lines that should be connected together.
In electrical nodes, it is hard to say the specific network layout that is used, at this stage, we may for example (a) move all the nodes with the same station_id AND voltage, together. Then, we could add "fake lines" (or trasformers) to link the buses at different voltages.
What do you think?

**Comment by pz-max** [comment]
Hi Davide, I reviewed your contributions. Great job :).

> The issue (1) is related to the fact that in our case, multiple buses correspond to the same substation.

A bus is defined as a line ending (bus_id). A substation originally in OSM as area (station_id). I believe it is correct that multiple line endings (bus_id's) should end up in one substation area (station_id). Do I understand it right: It seems we need a "geometric" connected network so that remove stubs works? We so far assumed having the lines with the correct station_id's solves everything. (when zooming in the pypsa network it seems that the line endings are also not merged exactly at the same point. However, this can be also a bug of the plot which might not be able to represent that?)

Does remove_stubs worked without the "fake lines"?


>  first I improved how those nodes are identified

Great. You created a tree of minimum bus distances & for buses that are close by you set a `stations_id`.


> I think we should "merge" nodes corresponding to lines that should be connected together.
> In electrical nodes, it is hard to say the specific network layout that is used, at this stage, we may for example (a) move all the nodes with the same station_id AND voltage, together. Then, we could add "fake lines" (or transformers) to link the buses at different voltages.


In any case, I think we can create a transformer dataframe at substations with multiple voltages AND merge at one station buses with the same voltage.

**Comment by davide-f** [comment]
> Hi Davide, I reviewed your contributions. Great job :).

Thank you, but too nice :)

> A bus is defined as a line ending (bus_id). A substation originally in OSM as area (station_id). I believe it is correct that multiple line endings (bus_id's) should end up in one substation area (station_id). Do I understand it right: It seems we need a "geometric" connected network so that remove stubs works?

That's what is seems; without that trick, the remove_stubs cannot run as it is now

> We so far assumed having the lines with the correct station_id's solves everything. (when zooming in the pypsa network it seems that the line endings are also not merged exactly at the same point. However, this can be also a bug of the plot which might not be able to represent that?)

I don't think it is a bug: in the buses dataframe there are >400 buses, most of them are really close each other (that's why we introduced substation_id). Correspondingly, the bus0 and bus1 in the lines dataframe are linking each line to it's endings, some of wich may be very close to other endings. Therefore, the graph that's described is not well connected.

> Does remove_stubs worked without the "fake lines"?

Unfortunately no
 
> Great. You created a tree of minimum bus distances & for buses that are close by you set a `stations_id`.

That's basically it

> In any case, I think we can create a transformer dataframe at substations with multiple voltages AND merge at one station buses with the same voltage.

Yeah, we are on the same page then.

**Comment by davide-f** [comment]
Regarding the second point of the list, the only one left, may we remove the clustering part from the simplify_network function so to manage it through snakemake?

**Comment by pz-max** [comment]
Closed by PR https://github.com/pypsa-meets-africa/pypsa-africa/pull/386
