### ISSUE TITLE
Buses mislabeled/mislocated to different countries

### ISSUE THREAD

**Issue by hazemakhalek** [pz-max/pypsa-africa#113]
While building the network for only 2 countries: Morocco and Algeria, I noticed that some of the buses on the base_network plot are located outside the 2 countries, specifically in Tunisia and Libya.
 
![NA_base_network](https://user-images.githubusercontent.com/87850910/136164773-8abf34b5-7729-43c2-8176-2122795fd0d4.PNG)

There is at least 4 mislocated/mislabeled buses in each of Tunisia and Libya. The coordinates of these buses in the base network actually lie outside Algeria, so there's no significant deviation with the plot.

Inspecting the raw generators, lines and substations, it seems that this might be, at least for most of the cases, a result of the cross border lines. The algorithm might be adding the bus to the end of these lines?
![image](https://user-images.githubusercontent.com/87850910/136166972-e41a5a24-dc8b-4e58-a43f-88a08d6b40e0.png)

This issue still persists after clustering, below is a yet-to-be-perfect 100-node clustered network of Morocco and Algeria:
![image](https://user-images.githubusercontent.com/87850910/136168117-ff5b56e3-ffd5-48f2-8c7c-2e27bebf745d.png)

In the next few days I will tryout the network with Tunisia and Lybia as well and see to which countries these buses are labeled. 
I believe this is probably just an issue that occurs at the borders of the network when the model is built for only a part of Africa.

**Comment by davide-f** [comment]
That is well known and we discussed it with @pz-max, which was taken into account in the solutions of  #96  and #103 .
The "actually wanted" issue arises only to crossborder lines and it is due to the current way substations are created: by adding endings to the lines. The other approach of using the dataset of osm_data, unfortunately, would limit significantly the number of buses. That's why we used the former approach.
One option was to remove crossborder lines outside the countries of interest, but that may be questionable; in this version we decided to keep the crossborder lines.

For this version I think this is not a prioritary issue, unless it creates problems in cluster_network or simplify_network.

**Comment by pz-max** [comment]
Maybe we can create a function after to "assign_bus_2_country"? @davide-f

**Comment by davide-f** [comment]
Actually, that function is already implemented as "set_countryname_by_shape" in the osm_data_cleaning.

The wanted/unwanted behavior that we are experiencing is mainly due to the dataset of the substations downloaded by osm data that is lacking and actually we are completely ignoring it: in the base_network code, the substations are created only by using the network data and labeling as nodes the endings of the line; the country of the endings is taken by the line

Clearly the above considerations arise when lines cross borders, which generates the following:
1. what to do with crossborder lines between countries within and without the area of interest? The current choice was to still keep them, but the above generates some nodes outside the area of interest.
2. how to manage crossborder lines between countries within the area of interest? This I believe is more relevant and annoying, in fact it had to be addressed. The easiest and most efficient way to tackle this is moving the "fix" discussed above from base_network to osm_data_cleaning. We may set an option(?) to ask whether to use the original osm dataset for the buses, or to generate it from the nodes. The most robust way, instead, is to join the two datasets and create out of osm_data_cleaning the substation data without these issues.

We could keep this issue open to keep this point in mind.
If we agree, I believe it is worth focusing on the rest and fix this later, it is slightly inaccurate, but it is not a priority, at least in my opinion. The fix is not "difficult" but it involves a software structuring given what discussed in point 2: the "disregard the substations" was intended to move on in the coding the other parts.
What do you think?
