### ISSUE TITLE
solve_network notebook indicates some bugs in previous .py scripts

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#130]

**Comment by pz-max** [comment]
On a fresh clone, still the same problem as we discovered a couple of weeks ago. (FYI @Hazem-IEG , @davide-f)
![image](https://user-images.githubusercontent.com/61968949/141808463-d1a8771f-3427-4423-bd2b-c65be9a47233.png)
I will debug the error this week.

**Comment by pz-max** [comment]
![image](https://user-images.githubusercontent.com/61968949/141809761-0eec08ae-407d-4d39-933b-26f372f584ec.png)

**Comment by davide-f** [comment]
I have been investigating this problem and I prepared a new notebook (network_characteristics_before_solve) for scouting the inputs of the PyPSA model before solving. I wrote it also including comments and description.

In particular, I noticed two problems:
- the capital_cost of the PV and wind assets was 0.0
- the specific production of the assets is the same for pv and wind, which is akward

See:
![image](https://user-images.githubusercontent.com/67809479/143456576-7c84f97a-1537-4f61-9cbb-4a82c1f1cf9a.png)

I have investigated the issue (1) and it was related to the fact that the "capital_cost" value, initialized as follows, ended up to be NaN because of the multiplication time Nyears that was a pandas Series, instead of a number
https://github.com/pypsa-meets-africa/pypsa-africa/blob/765e06fa03980cbd7ddb26268d440821d35127a4/scripts/add_electricity.py#L155-L157

Now, the capital cost is not null, yet the specific number shall be clarified.
![image](https://user-images.githubusercontent.com/67809479/143457296-5fb8775c-0109-4e3f-a499-8d39c9970bce.png)

**Comment by davide-f** [comment]
Results with commit f8c9cc807f4ac58a1504c5ddd24b04aaa097b00c seems more realistic than before: only solar is installed because it is cheaper than wind, given the current data filling procedure, yet to be improved.

See:
![image](https://user-images.githubusercontent.com/67809479/143459471-fdaeb4e5-3237-43d5-9d13-160eca520e67.png)

**Comment by davide-f** [comment]
The reason why the wind and solar production are the same lay in the fact that add_electricity is not complete.
I'll investigate to improve the issue.

https://github.com/pypsa-meets-africa/pypsa-africa/blob/f8c9cc807f4ac58a1504c5ddd24b04aaa097b00c/scripts/add_electricity.py#L330-L380

**Comment by davide-f** [comment]
With the last commit (6bd8e439084ab32f80a7bac842e70a8ccb0ed121) pretty simple actually, the results appear nicer more realistic, yet no powerplants are installed.
![image](https://user-images.githubusercontent.com/67809479/143472683-7d79ef89-fb46-4f99-a513-22d55dc4577e.png)

Main missing elements to be verified
- [x] other renewable sources (e.g. hydro): verify #162 , yet I can work on verifying if the add_electricity works fine using such data
- [x] thermal powerplants: need for solving #154

**Comment by davide-f** [comment]
With 4c1bf7115d3842484e430d1bb666aaa4d9ff9409, the conventional generators and hydro have been activated.
Hydro shall be better investigated, but it is enabled with a run-of-river.

![image](https://user-images.githubusercontent.com/67809479/143481743-2e406662-b401-49e3-ab40-6672dba8fe52.png)
