### ISSUE TITLE
.geojson data not recognized 

### ISSUE THREAD

**Issue by carlosfv92** [pz-max/pypsa-africa#340]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-africa/pypsa-africa/tree/main) branch or the latest [release](https://github.com/pypsa-meets-africa/pypsa-africa/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-africa` environment](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

Hi! I'm trying to run the model for a new region (SouthAmerica) and I followed the tips from the hackaton (the fifth file): installation of the cdsapi package, changed the config.yaml file to run only Bolivia (BO), enabled the build_cutout rule (true) and finally I replaced the landcover files of africa for southamerica. 

After that I run the model (snakemake -j 1 solve_all_networks) and an error appeared during the execution of the clean_osm_data rule which never occured before (when running the tutorial or variations). 

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
INFO:snakemake.logging:

ERROR:fiona._env:`resources/offshore_shapes.geojson' not recognized as a supported file format.
Traceback (most recent call last):
  File "fiona_shim.pyx", line 83, in fiona._shim.gdal_open_vector
  File "fiona_err.pyx", line 291, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: 'resources/offshore_shapes.geojson' not recognized as a supported file format.
```

**Comment by pz-max** [comment]
Thanks for reporting the bug. Copied solution from Discord:
1) delete data, resources, cutouts, networks and results folders (or create a backup)
2) make sure you are using the latest version of the repo (git pull)
3) run the following code: snakemake --cores all solve_all_networks --forceall
4) if all fail, plot the .geojson file which might give you hints to a solution

**Comment by pz-max** [comment]
Carlos:
Hey! so... I think I found the problem (or at least I have a theory):

As suggested, I pulled the latest version of the repo, deleted the cutots, networks and results folders (I only deleted the files that were generated in other runs in the data and resources folders since if I deleted the entire folder other rules started to present errors) and finally forced the model to run all the rules with the code you provided... The same error appeared.

I saw the .geojson files generated in the resources folder and it seems that the problem with the offshore_shapes.geojson file is that, given the case of Bolivia (mediterranean country), offshore_shapes are not properly generated (it can't be plotted / the file has a size of 0 kb)... and therefore something happens with the script when it tries to mix onshore and offshore maps/shapes? 

To check if this was the case I'm trying to run the model for Argentina (AR) and it already finished the rule clean_osm_data rule and is trying to download the files for building the cutout file (africa-2013-era5.nc)... so once this is finished, if everything is working, I'll give a more detailed look to the clean_osm_data script and see if I can change it so it works for Bolivia

**Comment by pz-max** [comment]
Bolivia has no offshore shape. It is not connected to the sea. So maybe we have an issue with empty offshore files. I saw a similar issue in Europe when someone planned to run PyPSA-EUR only in Austria (no offshore shape)

https://github.com/PyPSA/pypsa-eur/issues/265 . We need to debug this and make it possible to run everything without offshore shape.

**Comment by davide-f** [comment]
This issue is quite tricky and generalized as it applies anytime we use geojson format: when the dataframe is empty the file is not even created and we needed to create empty files to avoid snakemake to fail.

For compatibility purposes, why don't we get rid completely of geojson files and we use csv?
I feel like the only problem that arises is that the geometry column may not be automatically interpreted as a shapely geometry but all the problems related to missing files, empty columns and alike should disappear.
As alternatives, we could also consider other file formats but addressing all exceptions due to geojson has become too much patchy I think.
Any comments?

**Comment by pz-max** [comment]
@carlosfv92 check out the PR with the fix. It worked. Wherever offshore files are used, we can implement a similar fix as presented in the PR. I am pretty sure that some issues are happening later in other scripts with the landlocked stuff. I think it's a good exercise to contribute fixes for that purpose.
