### ISSUE TITLE
Remove code duplication in OSM network related code

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#415]
I was just checking the OSM code. It seems to me that we have some code duplications.

A. See build osm:
https://github.com/pypsa-meets-africa/pypsa-africa/blob/1d662a4c77e76d40a6ff36d383687614af6ab3ae/scripts/build_osm_network.py#L66-L105

B. And clean osm:
https://github.com/pypsa-meets-africa/pypsa-africa/blob/1d662a4c77e76d40a6ff36d383687614af6ab3ae/scripts/clean_osm_data.py#L75-L122

C. This function is also not used at any place:
https://github.com/pypsa-meets-africa/pypsa-africa/blob/1d662a4c77e76d40a6ff36d383687614af6ab3ae/scripts/build_osm_network.py#L37-L63

Can we remove C and merge A & B?   
Thoughts @davide-f & @ekatef

_Originally posted by @pz-max in https://github.com/pypsa-meets-africa/pypsa-africa/discussions/400_ with feedback from @ekatef

**Comment by davide-f** [comment]
So, in my opinion:
- C shall be removed
- Regarding A&B: if the clean_osm_data goes will be finalized into the OSM extractor that is not necessary to do now; otherwise, we may import a function from the other script and remove B I'd say, as long as the formulations are exactly identical and tested to be so

**Comment by davide-f** [comment]
I feel like this issue has been addressed and it can be closed. Closing
