### ISSUE TITLE
Total installed capacity changes after cluster network

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#431]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-africa/pypsa-africa/tree/main) branch or the latest [release](https://github.com/pypsa-meets-africa/pypsa-africa/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-africa` environment](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

After using cluster_network, the total installed capacity changes:

![image](https://user-images.githubusercontent.com/67809479/182883332-aac446b6-de3e-4259-a938-da3888a7b682.png)

The problem is mostly related to the clustering process and the use of sub_networks, which are not considered in the clustering procedure.
Enabling them, however explodes the number of minimum number of clusters needed to run the workflow

**Comment by pz-max** [comment]
Thanks for spotting this @davide-f. I am currently debugging the error. It appears not because of the sub_networks, but the `aggreagtion_strategies`. The aggregation strategies are triggered in the `simplify_network.py` (see [here](https://github.com/pypsa-meets-africa/pypsa-africa/blob/76bb53f622b4555b1a20106cca241d3d29551cba/scripts/simplify_network.py#L246-L249)) and imported from the [helpers](https://github.com/pypsa-meets-africa/pypsa-africa/blob/76bb53f622b4555b1a20106cca241d3d29551cba/scripts/_helpers.py#L325-L340). If no aggregation strategy values are given in the config, it will take the default values from `PyPSA/scripts/networkclustering`.

The below dictionary is given by `PyPSA` as default in the [network_clusterting ](https://github.com/PyPSA/PyPSA/blob/daead70515d877fd273cc294ffa1734c218f2831/pypsa/networkclustering.py#L61-L134
) script.  What you can see here is that when two points will be aggregated in terms of `p_nom`, only the min capacity will be taken. In the case of Nigeria this default setting reduced the `n.generators.p_nom.sum()` capacity from **7.7GW** to roughly **5GW**.  
```
    strategies = {
        "p_nom_max": pd.Series.min,
        "weight": pd.Series.sum,
        "p_nom": pd.Series.min,
        "capital_cost": pd.Series.sum,
        "efficiency": pd.Series.mean,
        "ramp_limit_up": pd.Series.mean,
        "ramp_limit_down": pd.Series.mean,
        "ramp_limit_start_up": pd.Series.mean,
        "ramp_limit_shut_down": pd.Series.mean,
        "build_year": lambda x: 0,
        "lifetime": lambda x: np.inf,
    }
```

I am extending now our already existing aggregation_dict in the config to read the `p_nom: sum`
  [aggregation_strategies](https://github.com/pypsa-meets-africa/pypsa-africa/blob/76bb53f622b4555b1a20106cca241d3d29551cba/config.default.yaml#L55-L64):
  ```
  aggregation_strategies:
    generators:
      **p_nom: sum**
      p_nom_max: sum # use "min" for more conservative assumptions
      p_nom_min: sum
      p_min_pu: mean
      marginal_cost: mean
      committable: any
      ramp_limit_up: max
      ramp_limit_down: max
      efficiency: mean
```

**Comment by pz-max** [comment]
FYI, the more you aggregate, the higher the error with the `p_nom: min` approach.
That's why you experience the tremendous capacity reduction from **120GW to 20GW**.
