### ISSUE TITLE
Calculate co2base depending on selected countries

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#488]
See the feature request raised in
https://github.com/PyPSA/pypsa-eur/issues/402

**Comment by Emre-Yorat89** [comment]
I am happy to tackle with this issue.

**Comment by pz-max** [comment]
@Emre-Yorat89 let us know if you have any questions or how we can support you.

**Conceptionally there are two things necessary:**
- We need to find a database with the 1990 values ideally differentiating between power & other sectors. Fabian references here the Database Edgar which at least includes the power-related emission: https://github.com/PyPSA/pypsa-eur/pull/89. Definetly worth exploring more. The database needs to be edited to include the country name for any country in the world as 3-letter code
- We need a function that check the countries in the `config.yaml` and calculates the 1990 base emissions

**Comment by ekatef** [comment]
@Emre-Yorat89  currently we have some functions to transform between a country name and country code in `_helpers`, for example:

https://github.com/pypsa-meets-earth/pypsa-earth/blob/c1de9272bcd28f74702139112e6d6a6964676048/scripts/_helpers.py#L451

https://github.com/pypsa-meets-earth/pypsa-earth/blob/c1de9272bcd28f74702139112e6d6a6964676048/scripts/_helpers.py#L493

**Comment by Emre-Yorat89** [comment]
v60_CO2_excl_short-cycle_org_C_1970_2018.xls dataset is preprocessed as described below.

- Second sheet namely "v6.0_EM_CO2_fossil_IPCC1996" is filtered out for Public electricity and heat production.
- Afterwards all 3 letter country codes is converted to iso2 code by country_converter package
- A function for getting two letter country code as a list and returning the emission values of the countries for 1990 in the list is developed. 

The unprocessed, processed dataset and the function is shared below. I am expecting your suggestions to correct my mistakes.

Note: The country_converter package were not able to convert the country "Netherlands Antilles (ANT)" to iso2. Therefore it is converted manually as AN. Also Serbia and Montenegro is abbreviated as CS manually too.
In some countries the emission values for "Public electricity and heat production" is empty. These countries are Turks and Caicos Islands, Ghana, Greenland, Nepal.
Also I apologize for my too late response. 

Dataset Source : https://edgar.jrc.ec.europa.eu/dataset_ghg60

[v60_GHG_CO2_excl_short-cycle_org_C_1970_2018.zip](https://github.com/pypsa-meets-earth/pypsa-earth/files/10567065/v60_GHG_CO2_excl_short-cycle_org_C_1970_2018.zip)
[co2_copy.xlsx](https://github.com/pypsa-meets-earth/pypsa-earth/files/10567071/co2_copy.xlsx)
[_emission_extractor.txt](https://github.com/pypsa-meets-earth/pypsa-earth/files/10567097/_emission_extractor.txt)

**Comment by pz-max** [comment]
> Also I apologize for my too late response.

No apology needed @Emre-Yorat89  :) Could you create a Pull Request? (thats how we can better collaborate, test and discuss the code) [Here](https://www.youtube.com/watch?v=HBubZEpIeXk&list=PLz1RcE1NdLlEzCT8G_v-sJKOeHOhZvw5R&index=7) is one out of our many training video's that you could checkout on how we do that.

**Comment by ekatef** [comment]
Hey @Emre-Yorat89! Great to hear from you :)

My feeling is that your have done a very good work and successfully addressed the first point on the tasks list. Congratulations and thanks a lot for working on this issue! It's really very helpful.

Regarding the geography and data questions you ask:

1) Ok for "AN" manual transformation for Netherlands Antilles. Not sure if we are able to include them into consideration right now. But with micro-grid PyPSA package it may be highly relevant. Thanks for spotting!

2) Regarding missed CO2 data: that is perfect that you have investigated that. Data availability is indeed a key question. I think for this case we could use some filling-missed approaches like taking values from other years.

A couple of suggestions on how to proceed further.

1) You have done absolutely relevant transformations on the original `v60_GHG_CO2_excl_short-cycle_org_C_1970_2018` file. However, I'm not sure if it makes sense to use the transformed file as a model input directly. I think that it's always best to keep the data source making data extraction and transformation in place when it's needed. So, I'd  add to the `emission_extractor( )` function also the procedures you developed to read and transform the original data.

What is you feeling about that?

2) `_emission_extractor.txt` module seems to do the job it's intended for. So, I think you can start to integrate it into the project and make a PR as Max suggests. As far as I can see from the code base, CO2base is being used in `prepare_network` script by `add_co2limit()` function. Which mean that we need the CO2 value you are extracting to define the inputs when calling this function, namely here:

https://github.com/pypsa-meets-earth/pypsa-earth/blob/4019a9f1df6dd248ed34ba8a7adad771a728bc0e/scripts/prepare_network.py#L282-L292

So, I think that it the place where the `emission_extractor( )` is needed and suggest to integrate it into this workflow. Do you agree?

**Comment by Emre-Yorat89** [comment]
Hello,
Thank you for your valuable suggestions @ekatef. :)
Then, I will also include the transformations in _emission_extractor()_ function and afterwards request a PR. 
One question is that is it appropriate to include the function _emission_extractor()_ in the prepare_network script? What would you suggest? 

Thank you for all the support.

**Comment by ekatef** [comment]
> Hello,
> 
> Thank you for your valuable suggestions @ekatef. :)
> 
> Then, I will also include the transformations in _emission_extractor()_ function and afterwards request a PR. 

@Emre-Yorat89, ok, great! Happy to help :) And thanks a lot for joining the development activities!

> One question is that is it appropriate to include the function _emission_extractor()_ in the prepare_network script? What would you suggest? 

I think that it perfectly appropriate :)

The only thing to be kept in mind when modifying the existing code is that it's (almost) always desirable to match the coding style to one assumed in the project. But that is just a technical side which can worked on in course of such code additions

**Comment by Emre-Yorat89** [comment]
Hello,
I had a PR that includes emission_extractor() function which outputs co2 emission values for given countries from the excel sheet. The only modification on the excel sheet I did was regarding to missed CO2 data which I have taken values from other years for Turks and Caicos Islands, Ghana, Greenland, Nepal.

I have listed my questions below,
- One question is how should I put excel data to data folder of pypsa-earth main?
- The other problem is Serbia and Montenegro is one country therefore one co2 emission value in the excel sheet. However, in the country list of config_osm_data script it is two separate countries having unique ISO2 codes.
- The most important problem for me is calling emission_extractor function in prepare_network script where add_co2limit() function is called as Katia mentioned. For this I will do an extra PR after taking your suggestions. I am confused here because currently it takes default values for co2limit from config.yaml script. Therefore, should i disable to take default emission values from config.yaml in prepare_network script or adding it as an option in which the user decides what to do. I would like to take your advices in this part.

**Comment by pz-max** [comment]
Hey @Emre-Yorat89,🚀
Seems we are getting close. This will be a great contribution.

Could you watch a video on how to create a PR (we shared some in the past on YouTube). Ideally you create a "draft Pull Request" for the next steps. Update. Sorry, just saw that you created a PR. Great! 👍🏽

Instead of storing the data in the repo, it would be good to automatically download it with Python if possible.

'download_emission_data()'
'prepare_emission_data()'
'export_emission_data()'

The 'prepare_network.py' can then read in the values in the config.yaml or if a new config option e.g. called automatic_emission_base_year: True it should read in the automatic emission data stuff

**Comment by Emre-Yorat89** [comment]
Hey,

- At the new commit, I have added download_emission_data() functionality and automatic_emission_base_year: in the config.default.yaml file. 

- I could test the code overall at the download_osm_data script and it has worked with no problem. I have copied necessary libraries and other codes to prepare_network.py script. In this regard, at the end of the prepare_network script I am not sure if the changes I have made is correct because currently co2limit is global for all countries. However, in the committed code the co2limit will be different for each country. Therefore I want to be make sure if this change does not break anything. https://github.com/pypsa-meets-earth/pypsa-earth/blob/7b005623096f8be2434a766107bce9e1432c7b8a/scripts/prepare_network.py#L326-L335 

- I have realized now that I missed "skiprows, to skip the first nine rows" suggestion in this commit @pz-max. However, I can try it with the corrections I have  to make in the next commit if you would like. 

Thank you :)

**Comment by ekatef** [comment]
Hello @Emre-Yorat89,

Nice to see the advancements you have made! I think your contribution looks great and will be definitely very helpful. You are absolutely right regarding the same co2limit assumed currently for every country of the world. That is indeed not perfectly correct and has to be checked/adjusted manually for model runs which include the CO2 constraint. Your PR fixes it in a very handy way.

My general impression is that your PR in a very good shape and might need only some minor adjustments. In particular, that it's worth to use `"Y_1990"` to navigate through the table. I have also added a few suggestions related to the technical part.

Thank you, too and happy to discuss further :)

**Comment by Emre-Yorat89** [comment]
Hello,

I have improved the code in the way that now column names can be used in navigating data. In some cases where old co2 emissions values before and on 1990 are not existed, nearest emission value to 1990 is used. I have included all in the PR. If I need to improve or need to change the code in some part I am happy to discuss and modify the PR.

Thank you for all the feedbacks and have a great day.
