### ISSUE TITLE
missing column with empty generators dataframe

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#704]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

When the generators data are empty, most likely problems appear in the aggregation phase.
To reproduce, let's set the country "TV" and drop all isolated nodes (using a high value of the threshold in simplify_network options).
This may be a bug to be highlighted into PyPSA

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
INFO:__main__:Removing stubs
Traceback (most recent call last):
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmpk7dzdv0z.simplify_network.py", line 746, in <module>
    n, stub_map = remove_stubs(
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmpk7dzdv0z.simplify_network.py", line 414, in remove_stubs
    _aggregate_and_move_components(
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmpk7dzdv0z.simplify_network.py", line 254, in _aggregate_and_move_components
    generators, generators_pnl = aggregategenerators(
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pypsa/networkclustering.py", line 81, in aggregategenerators
    weighting = generators.weight.groupby(grouper, axis=0).transform(normed_or_uniform)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'weight'
```

**Comment by davide-f** [comment]
@ekatef Since you have dealt with similar issues and in simplify_network/PyPSA, would you mind taking care of this issue?
I think once found the problem, it should be easy to address, most likely few lines of code.
What do you think?

If interested, you may clone my latest fork and debug from it: https://github.com/pypsa-meets-earth/pypsa-earth/pull/701

**Comment by ekatef** [comment]
@davide-f happy to take it.
Thank you ;)

**Comment by ekatef** [comment]
Have reproduced the issue for Falkland islands. Currently, there are no power plants there which would be known to powerplantmatching, as well as no generators extracted from OSM. However, that is not enough to reproduce the issue. One has to set `renewable_carriers` as an empty list, as otherwise renewable generators would appear in the model.

Looking into `add_electricity`, I think that lacking of renewable generators could be the primary trigger of the issue, as `weigh` column is being added for renewable generators only, not for conventional ones. 

It looks like `aggregategenerators` silently assumes that there are renewable carriers and at least a possibility to get a renewable generator somewhere in the system. That is why `weight` column should present in columns of `n.generators`. So, the question is why it's not the case for Tuvalu.

@davide-f does the above sound any reasonable for you? :)

**Comment by ekatef** [comment]
Update: an experiment for Argentina has allowed to reproduce the issue in case simulation settings doesn't allow any renewable generation to be included into the model (`renewable_carriers: [offwind-dc]` + some adjustments in `add_electricity` to avoid adding any hydro power). There are conventional generators, but due to omitting renewable power, `weight` column is missed which lead to the same troubles as in Tuvalu case
