### ISSUE TITLE
Add copy commit processing rule

### ISSUE THREAD

**Issue by doneachh** [pz-max/pypsa-africa#854]
Rule should create a txt file in the output which states the commit the model PyPSA-Earth did run on

**Comment by doneachh** [comment]
@pz-max i have implemented a copy commit processing rule for PyPSA-Earth-Sec recently:
https://github.com/pypsa-meets-earth/pypsa-earth-sec/pull/230

Do you think it makes sense to implement it in PyPSA-Earth as well?

**Comment by pz-max** [comment]
@doneachh looks like a cool feature to me. Instead of storing this in a .txt, I would prefer storing it in every config.yaml. Every resulting PyPSA networks (.nc) file currently stores the optimization inputs/results and the config it was run with (-> `n.config`. Having there the information of what commit the workflow was executed sounds valuable to me.

Can you make this happen somehow e.g. a comment in one of the first lines in the `n.config` OR what are your thoughts?

**Comment by doneachh** [comment]
@pz-max sounds great! I'll give it a try 👍
