### ISSUE TITLE
Generalize line_types

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#998]
## Describe the feature you'd like to see

I'd like that our line-voltage management strategy would extend beyond the fixed 3-type voltage lines to accommodate an arbitrary list of voltage levels.

To do so, on one hand, we need to revise:
- the handling of the line-type handling in build_osm_network. In particular, we shall revise [this function](https://github.com/pypsa-meets-earth/pypsa-earth/blob/d3d718b8e22fab344991a73a9f9637bf6f22ecb4/scripts/base_network.py#L284) to make sure that each line is matched with a line_type that is the closest among the provided ones. The same shall be extended also for DC lines by voltage
- avoid the rebase to config values here: https://github.com/pypsa-meets-earth/pypsa-earth/blob/d3d718b8e22fab344991a73a9f9637bf6f22ecb4/scripts/base_network.py#L440 . In the latest pypsa-eur this function is not needed anymore

**Comment by davide-f** [comment]
FYI @GbotemiB @ekatef 

Emmanuel, I remember you encountered an issue related to the recalculation of the nominal line capacity that was different in two calculations.
That may be the procedure we adopt for the line_type specification may fail in some cases:
https://github.com/pypsa-meets-earth/pypsa-earth/blob/d3d718b8e22fab344991a73a9f9637bf6f22ecb4/scripts/base_network.py#L284

The linetypes may not be set for some lines

**Comment by ekatef** [comment]
Hello @davide-f and thanks a lot for tagging!

Absolutely agree that it totally makes sense to set the line type as accurate as possible to improve representation of the transmission capacity. I can confirm after working with the notebooks by @GbotemiB (which are very insightful analysis tools), that `linetype` can effect the overall capacity very significantly.

I wonder if this change would also have any implications for reproducing the network structure? There is a fresh graph-related problem which may be connected with this issue. The point is if we'd try [to visualise a more or less meshed network as a graph](https://github.com/pypsa-meets-earth/network-comparison/pull/14#issuecomment-2016943872), the result resembles rather a dynamic chaos than a respectful network. I recognise that there the visualisation itself approach can be probably improved, but it feels like it may be a very good idea to account for different voltage levels instead of merging them all straight away.

At least, it looks line normally that is exactly the voltage level which determines the structure of the network meaning, e.g.:
<img width="359" alt="image" src="https://github.com/pypsa-meets-earth/pypsa-earth/assets/30229437/d5ce20a5-a640-4b0b-9420-6541497cdeed">
(the image taken from [here](https://arxiv.org/abs/1512.01436))
So, if I understand properly, keeping the voltage levels also allows to have a more accurate understanding of the network structure on a quite fundamental level, right?

However, before making structural transformation in `simplify_network`, we would anyway map all the voltages to the same level. So, not sure if keeping the original voltages makes a lot sense from the topological perspective, at the end.

Does it make sense for you? 🙂

**Comment by GbotemiB** [comment]
Thanks @davide-f for pointing this out. My 5 cents contribution is that we all agree that we need to find a way to resolve the rebasing of voltage values. We can also learn from pypsa-eur to see how they handle this section.

**Comment by GbotemiB** [comment]
> FYI @GbotemiB @ekatef
> 
> Emmanuel, I remember you encountered an issue related to the recalculation of the nominal line capacity that was different in two calculations. That may be the procedure we adopt for the line_type specification may fail in some cases:
> 
> https://github.com/pypsa-meets-earth/pypsa-earth/blob/d3d718b8e22fab344991a73a9f9637bf6f22ecb4/scripts/base_network.py#L284
> 
> The linetypes may not be set for some lines

I also agree that it is possible the linetypes may not be set for some lines.

**Comment by davide-f** [comment]
So, with this feature, I feel like all lines get assigned a line type and the issue you were experiencing should no more apply.
However, we need the rebasing to better account for power-flow dispatch analyses. However, the s_nom should not change because of the rebasing
